Adding error-middleware
full-stack-hardcore/teamup-server pull request #15
Opened 2018-08-20 22:09 UTC by lucasnachtigall

Issue #4

2018-08-20 23:37 UTC, gabrielsiedler requested changes

2018-08-20 23:37 UTC, gabrielsiedler commented on src/api/login/login.ts
> +            res.send(e)
```
// no need for try catch
if (err) {
  throw new BadRequestError('');
}
// no need for else, throw returns

res.json({
  ...
})

```

2018-08-20 23:37 UTC, gabrielsiedler commented on src/api/login/login.ts
> +            res.send(e)
Why are you calling the middleware `verifyToken` AND verifying token on the route?

2018-08-20 23:37 UTC, gabrielsiedler commented on src/api/login/login.ts
> +        res.send(e)
Never leak error directly from the server.
Return an `Internal error - talk to the admin` in the worst case.

The error-middleware already handles that. ONly throw your error and dont worry about it

2018-08-20 23:37 UTC, gabrielsiedler commented on src/api/login/login.ts
> +        res.send(e)
never throw error to the enduser.
no need for try/catch blocks;

The happy path call `next()` and the worst case throw error
here you could use `UnauthorizedError()`;

2018-08-20 23:37 UTC, gabrielsiedler commented on src/server.ts
> +
add it after the `app.use('/api', masterRouter);`

2018-08-22 00:23 UTC, lucasnachtigall commented on src/api/login/login.ts
> +        res.send(e)
Changes pushed

2018-08-22 19:53 UTC, gabrielsiedler requested changes

2018-08-22 19:53 UTC, gabrielsiedler commented on src/api/login/login.ts
>    }
what is that?!?!

2018-08-22 19:53 UTC, gabrielsiedler commented on src/api/login/login.ts
> +        res.send(e)
Why try catch? Still leaking the error

2018-08-23 01:09 UTC, gabrielsiedler approved these changes
LGTM

2018-08-23 01:38 UTC, merged